version: 2

jobs:
  build:
    docker:
      - image: circleci/node:carbon
    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - run: yarn lint
      - run: yarn test

  publish:
    docker:
      - image: circleci/node:carbon
    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - run: yarn semantic-release

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/

      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
